#!/bin/bash

#make sure user is logged in as root
if [[ $EUID -ne 0 ]]
then
   echo "This script must be run as root; run \"sudo -i\" this will log you into root." 
   exit 1
fi

#updating before install
sudo apt update -y 
wait

#install package
sudo apt install openvpn -y
wait

#create openvpn keys
cd /etc/openvpn
